### ISSUE TITLE
Can't add `null: false` to `@primary_key` 

### ISSUE THREAD

**Issue by sl1depengwyn** [bamorim/typed_ecto_schema#42]
```
** (ArgumentError) invalid option :null for field/3
    (ecto 3.11.1) lib/ecto/schema.ex:2379: Ecto.Schema.check_options!/3
    (ecto 3.11.1) lib/ecto/schema.ex:2017: Ecto.Schema.__field__/4
    lib/explorer/chain/address/name.ex:22: (module)
```

If more details are needed feel free to request it

**Comment by bamorim** [comment]
I'm afraid that would have to be implemented as an option on the typed_schema and typed_embedded_schema functions.
